### ISSUE TITLE
Documentation example won't work under MiniZinc 2.3.1

### ISSUE THREAD

**Issue by hectorpal** [unitn-sml/pyconstruct#1] opened 2019-08-06 18:46 UTC
I'm trying the OCR Equations prediction example in the Pyconstruct documentation.
https://unitn-sml.github.io/pyconstruct/quick_start.html

I patch around an issue in MiniZinc 
https://github.com/paolodragone/pymzn/issues/40

However, I'm facing two errors.
* `pyconstruct/domains/minizinc.py`
refers to pymzn.MiniZincUnknownError but it says it doesn't exists.
* `ssg.fit(eq.data, eq.target)` fails.
It seems a problem in the template application related to `loss_augmented_map`.

The arguments `params` in 
https://github.com/unitn-sml/pyconstruct/blob/17e80c075eb56ceca8df55d557c3be09cc0f6cc6/pyconstruct/domains/minizinc.py#L225
seems reasonable
`args= {'params': {'w': None, 'features': None, 'type': 'LinearModel'}, 'problem': 'loss_augmented_map', 'y_true': {'sequence': array([ 4,  8, 10,  1,  0,  3, 11,  1,  5,  1])}}`

Here are some versions I'm using for obtaining this error:
python 3.7.4
MarkupSafe-1.1.1 
appdirs-1.4.3 
cachetools-3.1.1 
jinja2-2.10.1 
joblib-0.13.2 
numpy-1.17.0 
pyconstruct-0.2.2 
pymzn-0.18.3 
scikit-learn-0.21.3 
scipy-1.3.0 
pyyaml (5.1.2)

Btw, it is possible that the installation documentation don't enforce installing pyyaml.

**Comment by hectorpal** [comment] 2019-08-07 13:56
Maybe a simple workaround would be to say or add add explicit requirements for Minizinc or pymzn versions where it is known to work.

**Comment by hectorpal** [comment] 2019-08-07 15:29
I managed to start running `pyconstruct/examples/equations/equations.py` in the released by:

* Patching Pymnz as explained in https://github.com/paolodragone/pymzn/issues/40
* In `pyconstruct/domains/minizinc.py`, changing `pymzn.MiniZincUnknownError` to just Exception
* Non-parallel: `-p 1`

I also patched  `pyconstruct/domains/minizinc.py` following the development branch, but I don't think it makes any difference in this case.

I'm using the solver gecode.

**Comment by paolodragone** [comment] 2019-08-13 08:48
Hi @hectorpal,

Thanks for using Pyconstruct!
It turns out that we need now to explicitly import `pymzn.templates` in order to use the package.
I also removed the dependency to Gurobi and removed the parallelism by default (it's still failing).
I've managed to run the equations example with Gecode, although it is quite a bit slower than Gurobi, so I had to add a a timeout. With the timeout the inference problems are solved only sub-optimally so it takes quite a lot of examples to converge to low loss. You can try to increase the timeout and see if convergence improves.
I'll close this issue for now, open it back if the problem is not fixed for you.

**Closed as completed by paolodragone** 2019-08-13 08:48 UTC
